[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; form-action https://formspree.io; frame-ancestors 'none'; img-src 'self' data:; media-src 'self'; script-src 'self' 'sha256-gkcW32h11l1x6mY7xvTQzJGWeRXMDI1Rho+7ViCGLWo=' 'sha256-mX+Bdl8lu44J/69smYZpbPYbKGwxATfkUoKoU+aSENg=' 'sha256-1DCxno5EQDjsj8pbv9CoLf7A6qzEw4lUpp6hdI0UJVs=' 'sha256-NOAsFAa1LYdSbua2mNV3o6/DhAUqLO7CyrnoRZOk3u4=' 'sha256-b6mm+BG4yj0FqkLFsa+fte4prDa7PFiXtDpRksGrfE0='; style-src 'self' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; connect-src 'self'; object-src 'none'; upgrade-insecure-requests"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
